### ISSUE TITLE
Preview feedback issue

### ISSUE THREAD

**Issue by nilslice** [extism/go-sdk#5]
Adding a new issue here to take feedback on the SDK while it's being actively developed.

**Comment by syke99** [comment]
Haven't run it yet, but finally got around to refactoring my application using the new SDK!! Super smooth, and loved it!! Also, I opened [this](https://github.com/extism/go-sdk/pull/14) PR to add convenience methods for setting/getting variables to/from a plugin 😎

**Comment by bhelx** [comment]
I think we've gotten through this period. If anyone has any more issues let's move the to specific github issues. Thank you to everyone who participated getting this SDK off the ground!
