### ISSUE TITLE
Consider updating wazero to use new optimizing backend

### ISSUE THREAD

**Issue by nilslice** [extism/go-sdk#50]
Recently Wazero released a new compiler that may make sense for Extism to use as a default, but it requires us to make some minor changes to the way we configure Wazero via our SDK. 

https://github.com/tetratelabs/wazero/releases/tag/v1.6.0

It seems to still be experimental and targets arm64 exclusively for the time being, which may be reason to leave it out until later. 

If we do change this to be the default, then we also may want to consider adding a configuration to use the other compiler instead. 

Curious to know others thoughts here!

**Comment by bhelx** [comment]
I think this is covered by this PR: https://github.com/extism/go-sdk/pull/64
