### ISSUE TITLE
Is extism.Plugin thread-safe?

### ISSUE THREAD

**Issue by Kikkon** [extism/go-sdk#63]
hi !
 I am currently using a static instance of extism.Plugin globally, and there might be concurrent calls to the call function from different requests. I would like to confirm if there will be any issues with this approach?  

（：btw：the experience with extism is truly excellent, especially when compared to using the wasm runtime directly.

**Comment by mhmd-azeez** [comment]
Hi, `extism.Plugin` is not thread-safe, meaning you can't call functions on the same instance concurrently. But it's designed to be lightweight. So you don't need to turn it into a global singleton.

**Comment by nilslice** [comment]
> （：btw：the experience with extism is truly excellent, especially when compared to using the wasm runtime directly.


well, thank you very much for saying so! we try very hard to make it helpful ☺️

**Comment by bhelx** [comment]
Hopefully the questions was answered here, though feel free to re-open if you want to discuss more!
