### ISSUE TITLE
Specify the runtime version clearly

### ISSUE THREAD

**Issue by hellodword** [extism/go-sdk#69]
When updating the runtime by [simply replacing a Wasm binary file](https://github.com/extism/go-sdk/commits/main/extism-runtime.wasm), I think it would be helpful to clearly include the version number in the update. This way, the version number can be quickly identified without having to run code or dig through commit messages.

**Comment by bhelx** [comment]
Thank you, I think that should be possible! We'd gladly accept a PR or we can put this into our backlog of tasks.
