### ISSUE TITLE
Not possible to call `plugin.Main.ExportedFunctionDefinitions` after PR#47

### ISSUE THREAD

**Issue by clarkmcc** [extism/go-sdk#78]
#47 introduced a private `module` type which prevents me from calling `plugin.Main.ExportedFunctionDefinitions`. Was the intentional, or can we provide a way to get those exported functions again? Also, this is a breaking change to the API of the library, should there have been a major version bump?

https://github.com/extism/go-sdk/blob/617bfe0de5bdbd69a6ffd8bb782afa884d2712a1/extism.go#L99

**Comment by nilslice** [comment]
Hi @clarkmcc! yes there was a breaking change, but Go versioning is a little wonky and we don't think this deserved a full v2 update which would have required us to start a new directory to host new APIs  - but apologies if this caught you by surprise.  

For listing exports in an Extism module, I'd recommend using another plugin call which is our Modsurfer tool compiled to wasm. Here's an old thread that covers the usage:

https://github.com/extism/extism/issues/714

**Comment by clarkmcc** [comment]
The modsurfer approach seems pretty involved for something that is already exposed by wazero. Not to mention it seems to be more resource intensive, is that true? I'm running a wazero in a resource constrained environment so running a separate wasm plugin, passing my whole module as bytes to that module are all allocations I'd like to avoid if possible.

Is there a reason we can't expose the wazero method that already does this?

**Comment by nilslice** [comment]
Ideally, nothing from the Wazero API is exposed from Extism. We try hard to keep the runtime APIs hidden from all the SDK layers. This is true for Wasmtime, JS/Web etc. The Wazero API may change and we do not want to be stuck pinned to a version only to keep some stability in Extism, so it's far better to not use Wazero APIs unless absolutely necessary

As far as resources go, you're already using Extism, so it's no additional dependency, and if you create an instance of this plugin once at your program initialization, you should be able to re-use the same instance for all of the calls to it. It should not be very resource intensive.

**Comment by clarkmcc** [comment]
Sadly we have to create a new plugin instance every time because plugins are not thread-safe (#63).

To your point about the API changes, you're already heavily impacted by changes to the wazero API because you allow callers to specify module/runtime configs, which is an extremely important feature by the way. I don't see a huge difference between letting the wazero configs bleed through the Extism API, but not letting the wazero `Module` bleed through the Extism API.

Even if there's a distinction there, couldn't Extism expose it's own method like `ExportedFunctionDefinitions`, and under the hood it would use wazero's implementation? If wazero's function changes, no problem, just change how Extism calls into wazero under the hood. In the worst case, let's say wazero gets rid of it entirely, then Extism can call this Modsurfer module under the hood.

Unfortunately allocations are a huge deal for us so running a separate wasm module before every invocation of our own wasm module isn't an option. But if this is your position, it's not the end of the world, we'll probably just maintain a fork of Extism to work around this limitation.

Also, if Extism decides to change the approach on this, my company is more than happy to do the work to make it happen, we're not necessarily giving these suggestions and then expecting someone else to do the work for us :), we're mainly looking to see if there's buy-off.

**Comment by nilslice** [comment]
I understand - but fewer APIs exposed is better - and I'd love to get rid of those exposed APIs too. I think it was a mistake to expose them but it was a faster solution to deliver the configurable settings vs layering indirection.  

This looks like it was actually changed pre-1.0 so it's been this way quite a while. 

With regard to the thread safety, you could put the modsurfer plugin on a background goroutine and send a message via channel to ask for the functions -- I think the slice of wasm bytes is passed by reference over a channel too so it could save the additional allocation until the plugin call would copy them. 

Feel free to look at what a more optimal API could be to contribute back - we'd be happy to consider it and for this Go-specific SDK, we have more flexibility to expose slightly different features than those that exist in other SDKs (since everything else but JS embeds Wasmtime and needs to have a pretty consistent API across language SDKs). 

Would be happy to review anything you share - even just a sketch!

**Comment by clarkmcc** [comment]
We'll work on a PR that works for us and you can take a look.

> I'd love to get rid of those exposed APIs too. I think it was a mistake to expose them.

Some of us are just using Extism as a shim to pass complex types around, and for that use-case, abstractions are actually worse, not better. For this use-case we like having full control over the modules, the runtimes, etc., we only use Extism as the complex type shim. Now that's certainly not all use-cases, but I just want to point out that for at least this use-case, abstraction is the enemy! 

One possible suggestion to meet both needs for the future: provide two packages, `extism` and `extismcore`, sort of like [zap](https://github.com/uber-go/zap) and [zapcore](https://github.com/uber-go/zap/tree/master/zapcore). The idea is that for most simple use-cases, you just stick with the `extism` package. It's the batteries-included option, has sane defaults, and has a stable API. The `extismcore` package would be used by `extism` under the hood. It would expose more of the underlying wazero APIs, it wouldn't be batteries included, and could certainly be excluded from any API stability guarantees. With an approach like this, you could accommodate both the simple use-cases, and the more nuanced ones. In my opinion it would be a bummer for this library to get less powerful and more specific to a certain type of use-case, in the name of abstraction. Anyways, just a data point for you to consider!

> With regard to the thread safety

This approach sadly still doesn't work for us. We can't afford to copy of a 10MB WASM module just to pull the names out, when it can be avoided by simply exposing a function in our own fork. I do appreciate your suggestions and trying to help us work inside the box though, we just don't have the luxury to throw memory around in a resource-constrained environment when we don't have to.

**Comment by clarkmcc** [comment]
#79 here's basically what we're going for.

**Comment by nilslice** [comment]
Released in v1.5.0! Thank you for the help
