### ISSUE TITLE
go-sdk tokio::time::sleep hanging

### ISSUE THREAD

**Issue by anderspitman** [extism/go-sdk#88]
Time functions weren't working at all until I added `wazero.NewModuleConfig().WithSysWalltime().WithSysNanosleep()`, but it's still hanging.

Minimal repro:

https://github.com/anderspitman/extism_go_sdk_time

**Comment by anderspitman** [comment]
Fixed by adding `wazero.NewModuleConfig().WithSysNanotime()`

**Comment by scottctaylor12** [comment]
Thank you @anderspitman! This documented issue just saved me a lot of time 😁
